apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Release.Name }}
  subsets:
    - name: {{ .Values.version }}
      labels:
        version: {{ .Values.version }}
