apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfpg.releaseNameVersionConfig" . }}
  labels:
    {{- include "sfpg.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      http:
        addr: {{ .Values.service.http.port }}
        timeout: 1s
      grpc:
        addr: {{ .Values.service.grpc.port }}
        timeout: 1s
