apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfpg.releaseNameConfig" . }}
  labels:
    {{- include "sfpg.labels" . | nindent 4 }}
  annotations:
    {{- include "sfpg.annotations" . | nindent 4 }}
data:
  config.yaml: |
    server:
      http:
        addr: {{ .Values.service.http.portString }}
        timeout: 1s
      grpc:
        addr: {{ .Values.service.grpc.portString }}
        timeout: 1s
