apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfpg.releaseNameVersion" . }}
  labels:
    {{- include "sfpg.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfpg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sfpg.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "sfpg.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "sfpg.image" . }}:{{ .Values.image.tag }}
          volumeMounts:
            - name: config-volume
              mountPath: /data/conf
          envFrom:
          {{- range .Values.image.configmaps }}
            - configMapRef:
                name: {{ . }}
          {{- if eq . "hosts-configmap"}}
              prefix: _
          {{- end}}
          {{- end}}
          {{- range .Values.image.secrets }}
            - secretRef:
                name: {{ . }}
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: {{ .Values.service.http.port }}
#            initialDelaySeconds: 1
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /readyz
#              port: {{ .Values.service.http.port }}
#            initialDelaySeconds: 10
#            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.redis.create -}}
        - name: redis
          image: redis #k8s.gcr.io/redis:e2e  # or just image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: {{ .Values.redis.port }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "sfpg.releaseNameVersionConfig" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
