apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "sfpg.labels" . | nindent 4 }}
  annotations:
    {{- include "sfpg.annotations" . | nindent 4 }}
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfpg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sfpg.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sfpg.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "sfpg.image" . }}:{{ .Values.image.tag }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.image.configVolume }}
              readOnly: true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http.port }}
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
          {{- if or .Values.image.configmaps .Values.image.secrets }}
          envFrom:
          {{- range .Values.image.configmaps }}
            - configMapRef:
                name: {{ . }}
          {{- end }}
          {{- range .Values.image.secrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - {{ include "sfpg.grpc_health_probe_addr" . }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - {{ include "sfpg.grpc_health_probe_addr" . }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.redis.create -}}
        - name: redis
          image: redis #k8s.gcr.io/redis:e2e  # or just image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: {{ .Values.redis.port }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "sfpg.releaseNameConfig" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
