{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "sfpg.gateway" . }}
  labels:
    {{- include "sfpg.labels" . | nindent 4 }}
  annotations:
    {{- include "sfpg.annotations" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .Values.service.http.extPort }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: {{ .Values.service.grpc.extPort }}
        name: grpc
        protocol: GRPC
      hosts:
        - "*"
{{- end }}
