{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sfpg.serviceAccountName" . }}
  labels:
    {{- include "sfpg.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "sfpg.annotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
