{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "sfpg.gateway" . }}
  http:
    - match:
        - uri:
            exact: /
        - uri:
            prefix: /api/{{ .Values.name }}/
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
