apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "node.gateway" . }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .Values.service.httpPort }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
