{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "node.gateway" . }}
  http:
    - match:
        - uri:
            exact: /
        - uri:
              prefix: /_nuxt/
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
      corsPolicy:
          allowOrigin:
              - "*"
          allowMethods:
              - POST
              - GET
              - DELETE
              - PATCH
              - OPTIONS
          allowCredentials: true
          allowHeaders:
              - "*"
{{- end }}
